import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "../globals.css";
import Header from "../components/atoms/Header";
import Footer from "../components/atoms/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="ball.svg"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body
        className={`${inter.className} flex flex-col min-h-screen bg-gray-50`}
      >
        <Header />
        <main className="container flex-grow px-4 py-8 mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
